# docker-compose for Pontoon development.
#
# Note: Requires docker-compose 1.10+.
version: "2"
services:
  # Pontoon base image
  # This image handles user creation and permissions, so that code can be
  # shared from your local folder into the docker container.
  base:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.base
    image: local/pontoon_base

  webapp.python3:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.py3.base
      args:
        - pythonversion=3.6.8
    image: local/pontoon_base

  # Webapp app
  webapp:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    image: local/pontoon
    env_file:
      - docker/config/webapp.env
    environment:
      - LOCAL_USER_ID=1000
    depends_on:
      - postgresql
    command: ["/app/docker/run_webapp.sh"]
    ports:
      - "8000:8000"
      - "3000:3000"
    volumes:
      - ./pontoon:/app/pontoon
      - ./frontend/src:/app/frontend/src
      - ./frontend/public:/app/frontend/public
      - ./tests:/app/tests
      # git is used to run only tests that changed
      - ./.git:/app/.git

  postgresql:
    build:
      context: ./docker/postgres
      dockerfile: ./Dockerfile
    environment:
      # Create the superuser account
      - POSTGRES_USER=pontoon
      - POSTGRES_PASSWORD=asdf
      - POSTGRES_DB=pontoon
