# docker-compose for Pontoon development.
#
# Note: Requires docker-compose 1.27+.
services:
  server:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
      target: server
    image: local/pontoon
    env_file:
      - docker/config/server.env
    depends_on:
      - postgresql
    ports:
      - '8000:8000'
    volumes:
      - ./pontoon:/app/pontoon
      - ./requirements:/app/requirements
      - ./translate:/app/translate
      - ~/.ssh:/home/pontoon/.ssh

  # Database
  postgresql:
    image: postgres:13.4
    environment:
      # Create the superuser account
      - POSTGRES_USER=pontoon
      - POSTGRES_PASSWORD=asdf
      - POSTGRES_DB=pontoon
    volumes:
      - pgdata:/var/lib/postgresql/data

# Persist database
volumes:
  pgdata: null
