# docker-compose for Pontoon development.
#
# Note: Requires docker-compose 1.10+.
version: "2"
services:
  # Pontoon base image
  # This image handles user creation and permissions, so that code can be
  # shared from your local folder into the docker container.
  base:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.base
    image: local/pontoon_base

  # Webapp app
  webapp:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    image: local/pontoon
    env_file:
      - docker/config/webapp.env
    environment:
      - LOCAL_USER_ID=1000
    depends_on:
      - postgresql
    command: ["/app/docker/run_webapp.sh"]
    ports:
      - "8000:8000"
      - "3000:3000"
    volumes:
      - .:/app
    entrypoint:
      - ./docker/entrypoint_webapp.sh

  postgresql:
    build:
      context: ./docker/postgres
      dockerfile: ./Dockerfile
    environment:
      # Create the superuser account
      - POSTGRES_USER=pontoon
      - POSTGRES_PASSWORD=asdf
      - POSTGRES_DB=pontoon
