name: JavaScript and Jinja linting

on:
  push:
    branches:
      - main
    paths:
      - '**.jinja'
      - '**.js'
      - '**.html'
      - '**.ts'
      - '**.tsx'
      - '**.css'
      - package.json
      - '.*eslint*'
      - '.*prettier*'
      - .github/workflows/js-lint.yml
  pull_request:
    branches:
      - main
    paths:
      - '**.jinja'
      - '**.js'
      - '**.html'
      - '**.ts'
      - '**.tsx'
      - '**.css'
      - package.json
      - '.*eslint*'
      - '.*prettier*'
      - .github/workflows/js-lint.yml
  workflow_dispatch:

jobs:
  eslint:
    name: eslint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with: { node-version: '22' }
      - name: Install dependencies
        run: npm ci
      - name: eslint
        run: npm run eslint

  prettier:
    name: prettier
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with: { node-version: '22' }
      - name: Install dependencies
        run: npm ci
      - name: prettier
        run: npm run check-prettier
